### PR TITLE
sync2: add CAS for AtomicBool

### PR DESCRIPTION
**Pull request by lance6716**

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
I'd suggest we investigate using https://github.com/uber-go/atomic in TiDB projects as it is a well maintained and high quality.

**Comment by lance6716** [comment]
> I'd suggest we investigate using https://github.com/uber-go/atomic in TiDB projects as it is a well maintained and high quality.

yes, DM has replaced to uber dependency a month ago.

**Comment by tisonkun** [comment]
@lance6716 thanks for your information! That sounds good. Then I'd suggest to do the same in TiDB replacing  https://github.com/ngaut/sync2 .

**Pull request closed without merging**
